export let selectGenres = [ 
  "All", 
  "Acoustic", 
  "Indie", 
  "Ambient", 
  "Audiobook", 
  "Blues", 
  "Classical", 
  "Comedy", 
  "Country",
  "Electronic", 
  "Experimental", 
  "Folk",
  "Funk",
  "Hip-Hop/Rap",
  "Holiday",
  "Jazz",
  "Kids",
  "Latin",
  "Metal",
  "Podcast",
  "Pop",
  "Punk",
  "R&B/Soul",
  "Reggae",
  "Rock",
  "Soundtrack",
  "Spoken Word",
  "Global",
];
export let selectBadges = [
  "All",
  "Featured",
];
export let selectLocations = [
  "All",
  "Africa",
  "Antarctica",
  "Asia",
  "Australia",
  "Europe",
  "North America",
  "South America",
];
export let selectBootlegs = [
  "All",
  "Accepted",
  "Not Accepted",
];
export let editGenres = [
  { id: 1, text: "Acoustic" },
  { id: 2, text: "Alternative/Indie" },
  { id: 3, text: "Ambient" },
  { id: 4, text: "Audiobook" },
  { id: 5, text: "Blues" },
  { id: 6, text: "Classical" },
  { id: 7, text: "Comedy" },
  { id: 8, text: "Dance/Electronic" },
  { id: 9, text: "Experimental" },
  { id: 10, text: "Flamenco" },
  { id: 11, text: "Folk" },
  { id: 12, text: "Global" },
  { id: 13, text: "Gospel" },
  { id: 14, text: "HipHop/Rap" },
  { id: 15, text: "Holiday" },
  { id: 16, text: "Jazz" },
  { id: 17, text: "Kids" },
  { id: 18, text: "Latin" },
  { id: 19, text: "Metal" },
  { id: 20, text: "Podcast" },
  { id: 21, text: "Pop" },
  { id: 22, text: "Punk" },
  { id: 23, text: "R&B/Soul" },
  { id: 24, text: "Reggae" },
  { id: 25, text: "Rock" },
  { id: 26, text: "Soundtrack" },
  { id: 27, text: "Spoken" },
  { id: 28, text: "Urban" },
  { id: 29, text: "Vocal" },
];
export let editLocations = [
  { id: 1, text: "Africa" },
  { id: 2, text: "Antarctica" },
  { id: 3, text: "Asia" },
  { id: 4, text: "Australia" },
  { id: 5, text: "Europe" },
  { id: 6, text: "North America" },
  { id: 7, text: "South America" },
];
export let editBadges = [
  { id: 1, text: "New" },
  { id: 2, text: "Featured" },
];
export let editBootlegs = [
  { id: 1, text: "Not Accepted" },
  { id: 2, text: "Accepted" },
  
];
 export let editTips = [
  { id: 1, text: "0.25" },
  { id: 2, text: "0.50" },
  { id: 3, text: "0.75" },
  { id: 4, text: "1.00" },
  { id: 5, text: "1.25" },
  { id: 6, text: "1.50" },
  { id: 7, text: "1.75" },
  { id: 8, text: "2.00" },
  { id: 8, text: "2.25" },
  { id: 8, text: "2.50" },
  { id: 8, text: "2.75" },
  { id: 8, text: "3.00" },
  { id: 8, text: "3.25" },
  { id: 8, text: "3.50" },
  { id: 8, text: "3.75" },
  { id: 8, text: "4.00" },
  { id: 8, text: "4.25" },
  { id: 8, text: "4.50" },
  { id: 8, text: "4.75" },
  { id: 8, text: "5.00" },

]; 

export let editLicenses = [
  { id: 1, text: "All rights reserved" },
  { id: 2, text: "Attribution Non-commercial No Derivatives" },
  { id: 3, text: "Attribution Non-commercial Share Alike" },
  { id: 4, text: "Attribution Non-commercial" },
  { id: 5, text: "Attribution No Derivatives" },
  { id: 6, text: "Attribution Share Alike" },
  { id: 7, text: "Attribution" },
]; 
export let editPayments = [
  { id: 1, text: "Wallet" },
  { id: 2, text: "Profit-Sharing Token" },
]; 